version: "2"
services:
  main:
    image: fast_api
    build:
      context: .
    depends_on:
      - postgres_database
    ports:
      - 8000:8000
    env_file:
      - ".env"

  postgres_database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adminadmin
      - POSTGRES_DB=postgres
    ports:
      - 5432
